// Paint color data for Chrysler do Brasil, 1970–1981.
// Códigos and names are from the O Retrovisor archive.
// Hex values are educated placeholders derived from each color's Portuguese name
// and are not authoritative — correct with real archival samples when available.
// `unconfirmed: true` marks entries whose code/name still need verification.

export const DATA = {
  1970: [
    { code: "BEY6", name: "AMARELO CARAJÁ",        hex: "#E0A82E" },
    { code: "BEA5", name: "AZUL ABAETÉ Metálico",  hex: "#2E4A6B" },
    { code: "BEA9", name: "AZUL PROFUNDO Metálico", hex: "#1E3050" },
    { code: "BEW2", name: "BRANCO POLAR",          hex: "#F3EFE6" },
    { code: "BEP9", name: "PRETO FORMAL",          hex: "#1A1A1A" },
    { code: "BEV7", name: "VERDE IMPERIAL",        hex: "#2F4A35", video: "KtUNxnks-f8" },
  ],
  1971: [
    { code: "BGY5",    name: "AMARELO BOREAL",          hex: "#DE5C1E", models: ["Charger R/T"], video: "J5uxLHuhZQo", photo: "1971-dodge-charger-rt-amarelo-boreal.jpg" },
    { code: "BGY6",    name: "AMARELO CARAJÁ",          hex: "#E0A82E" },
    { code: "BGA5",    name: "AZUL ABAETÉ Metálico",    hex: "#2E4A6B" },
    { code: "BGA9",    name: "AZUL PROFUNDO Metálico",  hex: "#1E3050" },
    { code: "BGW2/W3", name: "BRANCO POLAR",            hex: "#F3EFE6" },
    { code: "BGC5",    name: "CINZA BARILOCHE",         hex: "#9A9A95" },
    { code: "BGV6",    name: "OLIVA D'OIRO",            hex: "#7A6E2A" },
    { code: "BGY7",    name: "OURO ESPANHOL",           hex: "#C8962E", video: "xFf2uzChpTY" },
    { code: "BGP9",    name: "PRETO FORMAL",            hex: "#1A1A1A" },
    { code: "BGV3",    name: "VERDE FRONTEIRA",         hex: "#3A5A3A", video: "EVbKmYGCEpc" },
    { code: "BGV7",    name: "VERDE IMPERIAL",          hex: "#2F4A35", video: "l6zd6dM8lf4" },
    { code: "BGV4",    name: "VERDE MINUANO",           hex: "#4A6B45" },
    { code: "BGV2",    name: "VERDE TROPICAL",          hex: "#2D6A4A", models: ["Charger R/T"] },
    { code: "BGR4",    name: "VERMELHO ETRUSCO",        hex: "#8C1E22", video: "pVwBfcKvEpU" },
    { code: "BGR6",    name: "VERMELHO XAVANTE",        hex: "#7A1D2A" },
  ],
  1972: [
    { code: "Y5",  name: "AMARELO BOREAL",            hex: "#E8B842" },
    { code: "Y8A", name: "AMARELO ENXOFRE CÍTRICO",   hex: "#DCD23A" },
    { code: "A5",  name: "AZUL ABAETÉ Metálico",      hex: "#2E4A6B" },
    { code: "A7",  name: "AZUL NAUTICO Metálico",     hex: "#2A5278" },
    { code: "W3",  name: "BRANCO POLAR",              hex: "#F3EFE6" },
    { code: "R8",  name: "BURGUNDY Metálico",         hex: "#5E1A2A" },
    { code: "C4A", name: "CINZA FENIX Metálico",      hex: "#8E8E8A" },
    { code: "R5",  name: "MARROM CASTANHA Metálico",  hex: "#5A3A26", video: "D6hhKdACHVk" },
    { code: "M4",  name: "MARROM CLARO AZTECA",       hex: "#8A6A4A" },
    { code: "Y7",  name: "OURO ESPANHOL",             hex: "#C8962E" },
    { code: "P9",  name: "PRETO FORMAL",              hex: "#1A1A1A" },
    { code: "V6",  name: "TURQUESA AQUARIO",          hex: "#2E8A8E" },
    { code: "V3",  name: "VERDE FRONTEIRA",           hex: "#3A5A3A" },
    { code: "V7",  name: "VERDE IGARAPÉ Metálico",    hex: "#3F6B4A" },
    { code: "V4",  name: "VERDE MINUANO",             hex: "#4A6B45" },
    { code: "V2",  name: "VERDE TROPICAL",            hex: "#2D6A4A" },
    { code: "R4",  name: "VERMELHO ETRUSCO",          hex: "#8C1E22" },
    { code: "R6",  name: "VERMELHO XAVANTE",          hex: "#7A1D2A", video: "j_BkA1bBLUU" },
  ],
  1973: [
    { code: "Y8A", name: "AMARELO ENXOFRE CÍTRICO",   hex: "#DCD23A" },
    { code: "A6A", name: "AZUL GUAÍBA",               hex: "#3A6F95" },
    { code: "W2",  name: "BRANCO IPANEMA",            hex: "#F1EDE4" },
    { code: "C4A", name: "CINZA CLARO HIMALAIA",      hex: "#C2C2BC", video: "LVAB9Rt4kN8" },
    { code: "C7",  name: "CINZA ESCURO",              hex: "#5A5A56" },
    { code: "M4",  name: "MARROM CLARO AZTECA",       hex: "#8A6A4A" },
    { code: "M8",  name: "MARROM ESCURO PILÃO",       hex: "#4A2E1E" },
    { code: "P9A", name: "PRETO TURANDOT",            hex: "#1A1A1A" },
    { code: "V6",  name: "TURQUESA AQUARIO",          hex: "#2E8A8E", video: "76FRewBrnOE" },
    { code: "G4",  name: "VERDE CLARO FLORESTAL",     hex: "#5A7A45" },
    { code: "G5",  name: "VERDE MEDIO AMAZONAS",      hex: "#356B48" },
    { code: "R4A", name: "VERMELHO CLARO / INDIO",    hex: "#B0382A" },
    { code: "R9",  name: "VERMELHO ESCURO CARDEAL",   hex: "#6E1A22" },
    { code: "R5",  name: "VERMELHO MEDIO NASCENTE",   hex: "#9A2418" },
    { code: "R3",  name: "VERMELHO TUDOR",            hex: "#8C1E22" },
  ],
  1974: [
    { code: "Y8A", name: "AMARELO ENXOFRE CÍTRICO",      hex: "#DCD23A", video: "F6XKeqhpCMA" },
    { code: "A5",  name: "AZUL CLARO MARUJO",            hex: "#6E95B8", unconfirmed: true },
    { code: "B7",  name: "AZUL ESCURO BAHAMA",           hex: "#1E3050" },
    { code: "W2",  name: "BRANCO IPANEMA",               hex: "#F1EDE4", video: "H0k6sKMbrX4" },
    { code: "T4",  name: "BRONZE CASTANHO BRILHANTE",    hex: "#7A5A2E" },
    { code: "A6B", name: "CINZA PLATINA",                hex: "#B8B5AD" },
    { code: "T9",  name: "MARROM CLÁSSICO",              hex: "#5A3A26" },
    { code: "Y6A", name: "OCRE/AMARELO BARROCO",         hex: "#C8962E", video: "MO1EZ6n-MPI" },
    { code: "P9A", name: "PRETO TURANDOT",               hex: "#1A1A1A" },
    { code: "G9",  name: "VERDE CORDOBA",                hex: "#3A5A3A" },
    { code: "G6",  name: "VERDE SILVESTRE",              hex: "#4A6B3A" },
    { code: "R4A", name: "VERMELHO CLARO / INDIO",       hex: "#B0382A" },
    { code: "R3A", name: "VERMELHO TUDOR",               hex: "#8C1E22" },
  ],
  1975: [
    { code: "LY3", name: "AMARELO MONTEGO",           hex: "#E8B842" },
    { code: "LB7", name: "AZUL MEIA NOITE",           hex: "#1F2F50" },
    { code: "LB6", name: "AZUL VITÓRIA",              hex: "#2E4A6B", unconfirmed: true },
    { code: "LW2", name: "BRANCO VALENCIA",           hex: "#F3EFE6" },
    { code: "LT2", name: "CASTANHO CORSA",            hex: "#6A4527" },
    { code: "LT9", name: "MARROM CLÁSSICO",           hex: "#5A3A26" },
    { code: "LS2", name: "PRATA LUNAR",               hex: "#B8B5AD" },
    { code: "LX9", name: "PRETO BAIXO BRILHO/ONIX",   hex: "#1A1A1A" },
    { code: "LF2", name: "VERDE AUSTRÍACO",           hex: "#2F4A35", unconfirmed: true },
    { code: "LG4", name: "VERDE PINHO",               hex: "#2F4A32" },
    { code: "LR7", name: "VERMELHO AZTECA",           hex: "#9A2418" },
    { code: "LR3", name: "VERMELHO DINASTIA",         hex: "#7D1C2E" },
  ],
  1976: [
    { code: "MY2", name: "AMARELO TENERIFE",          hex: "#E8B842" },
    { code: "LW2", name: "BRANCO VALENCIA",           hex: "#F3EFE6" },
    { code: "MY6", name: "CASTANHO ARAGUAIA",         hex: "#6A4527" },
    { code: "MY9", name: "MARROM IGUAÇU",             hex: "#5A3A26" },
    { code: "MA2", name: "PRATA MONTEREY",            hex: "#B8B5AD" },
    { code: "LX9", name: "PRETO BAIXO BRILHO/ONIX",   hex: "#1A1A1A" },
    { code: "MQ4", name: "TURQUESA MONACO",           hex: "#2E8A8E" },
    { code: "MF2", name: "VERDE JADE",                hex: "#3F7560" },
    { code: "LR3", name: "VERMELHO DINASTIA",         hex: "#7D1C2E" },
    { code: "ME9", name: "VERMELHO VENEZA",           hex: "#8C1E22" },
  ],
  1977: [
    { code: "NT2", name: "BEGE INDIANO",              hex: "#CDB88A" },
    { code: "LW2", name: "BRANCO VALENCIA",           hex: "#F3EFE6" },
    { code: "MY6", name: "CASTANHO ARAGUAIA",         hex: "#6A4527" },
    { code: "MY9", name: "MARROM IGUAÇU",             hex: "#5A3A26" },
    { code: "MA2", name: "PRATA MONTEREY",            hex: "#B8B5AD" },
    { code: "LX9", name: "PRETO BAIXO BRILHO/ONIX",   hex: "#1A1A1A" },
    { code: "NE4", name: "VERMELHO RIVIERA",          hex: "#9A2418" },
    { code: "ME9", name: "VERMELHO VENEZA",           hex: "#8C1E22" },
  ],
  1978: [
    { code: "PK3", name: "AMARELO ALAMO",             hex: "#E0A82E" },
    { code: "PB2", name: "AZUL CAPRI",                hex: "#3A6F95" },
    { code: "NT2", name: "BEGE INDIANO",              hex: "#CDB88A" },
    { code: "PW1", name: "BRANCO MADAGASCAR",         hex: "#F3EFE6" },
    { code: "PT3", name: "CASTANHO TRIPOLI",          hex: "#6A4527" },
    { code: "PT1", name: "OURO TOLEDO",               hex: "#C8962E", video: "JaLAf5TUZFA" },
    { code: "LX9", name: "PRETO BAIXO BRILHO/ONIX",   hex: "#1A1A1A" },
    { code: "PE7", name: "VERMELHO VERONA",           hex: "#8C1E22" },
  ],
  1979: [
    { code: "SB3", name: "AZUL CADETE",                          hex: "#4A6B8A" },
    { code: "SB9", name: "AZUL ESTELAR",                         hex: "#2A4A78" },
    { code: "AZ1", name: "AZUL ESTELAR/AZUL CADET",              hex: "#2A4A78" },
    { code: "ST2", name: "BEGE CASHMIRE",                        hex: "#D7C39A" },
    { code: "SW1", name: "BRANCO ARTICO",                        hex: "#F1EDE4" },
    { code: "SA2", name: "CINZA BALTICO",                        hex: "#8E8E8A" },
    { code: "PR1", name: "CINZA BALTICO/PRETO BAIXO BRILHO",     hex: "#5A5A56" },
    { code: "ST5", name: "MARROM SUMATRA",                       hex: "#5A3A26" },
    { code: "MA1", name: "MARROM SUMATRA/BEGE CASHEMIRE",        hex: "#8A6A4A" },
    { code: "LX9", name: "PRETO BAIXO BRILHO/ONIX",             hex: "#1A1A1A" },
    { code: "SR5", name: "VERMELHO ALCAZAR",                     hex: "#8C1E22" },
  ],
  1980: [
    { code: "SB3",     name: "AZUL CADETE",                hex: "#4A6B8A" },
    { code: "TB2/TC2", name: "AZUL GEADA",                 hex: "#8EA8C2" },
    { code: "TT4",     name: "BEGE/CASTANHO CAMURÇA",      hex: "#B89A6E" },
    { code: "SW1",     name: "BRANCO ARTICO",              hex: "#F1EDE4" },
    { code: "TA4",     name: "CINZA POLY",                 hex: "#9A9A95" },
    { code: "L8B",     name: "MARROM CAFÉ",                hex: "#4A2E1E" },
    { code: "TT8",     name: "MARROM CALCUTÁ",             hex: "#5A3A26" },
    { code: "TA3",     name: "PRATA TIBET",                hex: "#B8B5AD" },
    { code: "LX9",     name: "PRETO BAIXO BRILHO/ONIX",    hex: "#1A1A1A" },
    { code: "SR5",     name: "VERMELHO ALCAZAR",           hex: "#8C1E22" },
  ],
  1981: [
    { code: "L8A", name: "BEGE PALHA",                hex: "#D8C89A" },
    { code: "L9A", name: "BRANCO PAINA",              hex: "#F3EFE6" },
    { code: "L7C", name: "CINZA CHUMBO",              hex: "#5A5A56" },
    { code: "L8C", name: "MARROM AVELA",              hex: "#8A6A4A" },
    { code: "L8B", name: "MARROM CAFÉ",               hex: "#4A2E1E" },
    { code: "LX9", name: "PRETO BAIXO BRILHO/ONIX",   hex: "#1A1A1A" },
    { code: "L6A", name: "VERDE TURMALINA",           hex: "#2D6A4A" },
    { code: "L3A", name: "VERMELHO CALIPSO",          hex: "#9A2418" },
  ],
};

// Sort each year alphabetically by color name (pt-BR aware).
for (const y of Object.keys(DATA)) {
  DATA[y].sort((a, b) => a.name.localeCompare(b.name, "pt-BR", { sensitivity: "base" }));
}

export const YEARS = Object.keys(DATA).map(Number).sort((a, b) => a - b);

// Car models with their production-year ranges.
export const MODELS = [
  { name: "1800",        from: 1973, to: 1975 },
  { name: "Polara",      from: 1976, to: 1981 },
  { name: "Charger",     from: 1971, to: 1981 },
  { name: "Charger R/T", from: 1971, to: 1981 },
  { name: "Dakota",      from: 1998, to: 2002 },
  { name: "Dart Sedã",   from: 1970, to: 1981 },
  { name: "Dart Coupé",  from: 1970, to: 1981 },
  { name: "LeBaron",     from: 1979, to: 1980 },
  { name: "Magnum",      from: 1979, to: 1981 },
];

// Models available in a given year, in the canonical list order.
export function modelsForYear(year) {
  return MODELS.filter((m) => year >= m.from && year <= m.to).map((m) => m.name);
}
